---
# Задачи установки и настройки Fail2ban

- name: Установка fail2ban
  ansible.builtin.apt:
    name: fail2ban
    state: present
    update_cache: true
    cache_valid_time: 3600

- name: Создание локальной конфигурации fail2ban
  ansible.builtin.template:
    src: jail.local.j2
    dest: /etc/fail2ban/jail.local
    owner: root
    group: root
    mode: '0644'
  notify: Перезапуск fail2ban

- name: Включение и запуск fail2ban
  ansible.builtin.service:
    name: fail2ban
    state: started
    enabled: true
